import { createHash } from 'node:crypto';
import { hostname } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const pluginPath = resolve(dirname(fileURLToPath(import.meta.url)), '../adapters/dsh.mjs');
const quote = value => `'${value.replace(/'/g, "'\\''")}'`;

export function dshConnection(dataDir, endpoint) {
  const tokenFile = join(dataDir, 'ingest.token');
  const patchPath = join(dataDir, 'dsh-observer.generated.patch.yml');
  const instanceId = `dsh-${createHash('sha256').update(`${hostname()}\0${dataDir}`).digest('hex').slice(0, 16)}`;
  const patch = [
    '# Generated by Agent Symphony. This file does not alter your dsh home/profile.',
    '- insert:',
    '    - id: agent-symphony',
    `      name: ${JSON.stringify(pluginPath)}`,
    '      config:',
    `        endpoint: ${JSON.stringify(endpoint)}`,
    `        tokenFile: ${JSON.stringify(tokenFile)}`,
    `        instanceId: ${JSON.stringify(instanceId)}`,
    '        label: "dsh 本地会话"',
    '        backfill: true',
    '',
  ].join('\n');
  return { endpoint, tokenFile, pluginPath, instanceId, patchPath, patch, command: `dsh --profile headless --patch ${quote(patchPath)}` };
}
